<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-30T12:52:13 PKT" name="Default suite" finished-at="2023-03-30T12:56:22 PKT" duration-ms="248943">
    <groups>
    </groups>
    <test started-at="2023-03-30T12:52:13 PKT" name="Default test" finished-at="2023-03-30T12:56:22 PKT" duration-ms="248943">
      <class name="tests.Athlete_Tests">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.Athlete_Tests@6c1a5b54]" started-at="2023-03-30T12:52:13 PKT" name="setup" finished-at="2023-03-30T12:52:23 PKT" duration-ms="9495" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="firsttestcase()[pri:1, instance:tests.Athlete_Tests@6c1a5b54]" started-at="2023-03-30T12:52:23 PKT" name="firsttestcase" finished-at="2023-03-30T12:53:33 PKT" duration-ms="69763" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firsttestcase -->
        <test-method signature="secondtestcase()[pri:2, instance:tests.Athlete_Tests@6c1a5b54]" started-at="2023-03-30T12:53:33 PKT" name="secondtestcase" finished-at="2023-03-30T12:54:48 PKT" duration-ms="75274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondtestcase -->
        <test-method signature="thirddtestcase()[pri:3, instance:tests.Athlete_Tests@6c1a5b54]" started-at="2023-03-30T12:54:48 PKT" name="thirddtestcase" finished-at="2023-03-30T12:55:14 PKT" duration-ms="26005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirddtestcase -->
        <test-method signature="fourthtestcase()[pri:4, instance:tests.Athlete_Tests@6c1a5b54]" started-at="2023-03-30T12:55:14 PKT" name="fourthtestcase" finished-at="2023-03-30T12:55:53 PKT" duration-ms="39471" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fourthtestcase -->
        <test-method signature="fifthtestcase()[pri:5, instance:tests.Athlete_Tests@6c1a5b54]" started-at="2023-03-30T12:55:53 PKT" name="fifthtestcase" finished-at="2023-03-30T12:56:22 PKT" duration-ms="28694" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [03/28/10] but found [03/30/10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [03/28/10] but found [03/30/10]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at tests.Athlete_Tests.fifthtestcase(Athlete_Tests.java:252)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fifthtestcase -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.Athlete_Tests@6c1a5b54]" started-at="2023-03-30T12:56:27 PKT" name="teardown" finished-at="2023-03-30T12:56:27 PKT" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.Athlete_Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
